version: '3.1'

services: 
  
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: hackaton_usr
      POSTGRES_PASSWORD: hackaton_pwd
      POSTGRES_DB: hackaton  
        
  hackaton: 
    image: elessarfs/hackaton-fiap-grupo50:latest
    ports:
      - 8080:8080  
